version: "3"

services:
  raga:
    container_name: raga
    build:
      context: .
      dockerfile: Dockerfile.solo
    restart: always
    ports:
      - 3001:3000
    networks:
      - valiantlynx-turborepo

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  valiantlynx-turborepo:
    external: false
